//! Regulatory type system with compile-time enforcement
//!
//! This crate provides the type-level enforcement of spectrum regulations.
//! It uses types generated by the policy-compiler to ensure that:
//! - Transmit functions require a license typed to the specific band
//! - License expiry is enforced via lifetime parameters
//! - Coordination proofs are type-checked
//!
//! The key insight: if you don't have the license for a band, your code
//! doesn't compile. This is compile-time enforcement, not runtime checking.

pub mod types;
pub mod license;
pub mod transmit;
pub mod enforcement;

pub use types::{Band, Frequency, Power};
pub use license::{License, LicenseStore};
pub use transmit::{TransmitError, transmit};
pub use enforcement::{ComplianceChecker, ComplianceResult};
