//! Core regulatory types
//!
//! These are the foundational types used for compile-time enforcement.
//! Band-specific types are generated by the policy-compiler.

use std::marker::PhantomData;

/// Band trait - all band marker types implement this
pub trait Band: 'static {
    /// Band name
    const NAME: &'static str;
    /// Minimum frequency in Hz
    const MIN_FREQUENCY: u64;
    /// Maximum frequency in Hz
    const MAX_FREQUENCY: u64;
}

/// Frequency typed to a specific band
#[derive(Debug, Clone, Copy)]
pub struct Frequency<B: Band> {
    pub hz: u64,
    _band: PhantomData<B>,
}

impl<B: Band> Frequency<B> {
    /// Create a new frequency for this band
    pub fn new(hz: u64) -> Option<Self> {
        if hz >= B::MIN_FREQUENCY && hz <= B::MAX_FREQUENCY {
            Some(Self {
                hz,
                _band: PhantomData,
            })
        } else {
            None
        }
    }
    
    /// Get the frequency in Hz
    pub fn hz(&self) -> u64 {
        self.hz
    }
}

/// Power level in dBm
#[derive(Debug, Clone, Copy)]
pub struct Power {
    pub dbm: f64,
}

impl Power {
    pub fn new(dbm: f64) -> Self {
        Self { dbm }
    }
    
    /// Convert to watts
    pub fn to_watts(&self) -> f64 {
        10.0_f64.powf((self.dbm - 30.0) / 10.0)
    }
    
    /// Create from watts
    pub fn from_watts(watts: f64) -> Self {
        Self {
            dbm: 10.0 * watts.log10() + 30.0,
        }
    }
}

/// Coordination proof for a band
#[derive(Debug, Clone)]
pub struct CoordinationProof<B: Band> {
    pub coordinated_with: Vec<String>,
    pub coordination_date: chrono::DateTime<chrono::Utc>,
    _band: PhantomData<B>,
}

impl<B: Band> CoordinationProof<B> {
    pub fn new(coordinated_with: Vec<String>) -> Self {
        Self {
            coordinated_with,
            coordination_date: chrono::Utc::now(),
            _band: PhantomData,
        }
    }
}

// Example band types (these would be generated by policy-compiler)
// For demonstration, we include basic band types here

/// L-band marker type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct LBand;

impl Band for LBand {
    const NAME: &'static str = "L-band";
    const MIN_FREQUENCY: u64 = 1_000_000_000;
    const MAX_FREQUENCY: u64 = 2_000_000_000;
}

/// S-band marker type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SBand;

impl Band for SBand {
    const NAME: &'static str = "S-band";
    const MIN_FREQUENCY: u64 = 2_000_000_000;
    const MAX_FREQUENCY: u64 = 4_000_000_000;
}

/// C-band marker type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct CBand;

impl Band for CBand {
    const NAME: &'static str = "C-band";
    const MIN_FREQUENCY: u64 = 4_000_000_000;
    const MAX_FREQUENCY: u64 = 8_000_000_000;
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_frequency_construction() {
        let valid = Frequency::<LBand>::new(1_500_000_000);
        assert!(valid.is_some());
        
        let invalid = Frequency::<LBand>::new(3_000_000_000); // Outside L-band
        assert!(invalid.is_none());
    }
    
    #[test]
    fn test_power_conversion() {
        let power = Power::new(30.0); // 1 watt
        assert!((power.to_watts() - 1.0).abs() < 0.01);
        
        let power = Power::from_watts(1.0);
        assert!((power.dbm - 30.0).abs() < 0.01);
    }
}
