[package]
name = "tracking"
version.workspace = true
edition.workspace = true

[dependencies]
ground-core = { path = "../core" }
caching = { path = "../caching" }
batching = { path = "../batching" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
sgp4 = { workspace = true }
nalgebra = { workspace = true }
